modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/lehjr/ModularPowerArmor/issues"
logoFile="assets/modularpowerarmor/textures/logo.png"
license="All rights reserved"
[[mods]]
    modId="modularpowerarmor"
    version="${version}"
    displayName="Modular Power Armor"
    description='''
A mod which adds modular power armor, power tool, and a tinker table to configure them. Uses FE (Foreg Energy), EU (IndustrialCraft 2) or RF (Thermal Expansion 4).
'''
    authors="Code by MachineMuse, Lehjr and others"
    credits="Icons by WaterCandle, Modeling by SebK"

[[dependencies.modularpowerarmor]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.modularpowerarmor]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.modularpowerarmor]]
    modId="mpalib"
    mandatory=true
    versionRange="[2.0.2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.modularpowerarmor]]
    modId="centralizedmaterials"
    mandatory=false
    versionRange="[1.0.0,)"
    ordering="AFTER"
    side="BOTH"
